# MongoDB Configuration for PASS24 (Docker standalone)

storage:
  dbPath: /data/db
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.5

systemLog:
  destination: file
  path: /proc/1/fd/1
  logAppend: false

net:
  port: 27017
  bindIp: 0.0.0.0

security:
  authorization: disabled

operationProfiling:
  slowOpThresholdMs: 100
  mode: slowOp